# Generated by Django 4.2 on 2023-04-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_added_primary_ids'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
    ]
